In [1]:
import numpy as np
import pandas as pd

df = pd.DataFrame({
    'text': [
        'people watch campusx',
        'campusx watch campusx',
        'people write comment',
        'campusx write comment'
    ],
    'output': [1, 1, 0, 0]
})

df

from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer()

bow = cv.fit_transform(df['text'])

In [3]:
cv.vocabulary_

{'people': 2, 'watch': 3, 'campusx': 0, 'write': 4, 'comment': 1}

In [5]:
print(bow[0].toarray()) # order-->  campusx comment people watch write

[[1 0 1 1 0]]


In [6]:
cv.transform(['hi am am campusx how are u people']).toarray()

array([[1, 0, 1, 0, 0]], dtype=int64)

In [7]:
from sklearn.feature_extraction.text import CountVectorizer

In [10]:
cv = CountVectorizer(ngram_range=(2,2))
bow1 = cv.fit_transform(df['text'])

In [18]:
len(cv.vocabulary_.items())

6

In [19]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [20]:
tfidf = TfidfVectorizer()
tfidf.fit_transform(df['text']).toarray()

array([[0.49681612, 0.        , 0.61366674, 0.61366674, 0.        ],
       [0.8508161 , 0.        , 0.        , 0.52546357, 0.        ],
       [0.        , 0.57735027, 0.57735027, 0.        , 0.57735027],
       [0.49681612, 0.61366674, 0.        , 0.        , 0.61366674]])

In [21]:
print(tfidf.idf_)

[1.22314355 1.51082562 1.51082562 1.51082562 1.51082562]


In [23]:
tfidf.get_feature_names_out()

array(['campusx', 'comment', 'people', 'watch', 'write'], dtype=object)

In [24]:
tfidf.vocabulary_

{'people': 2, 'watch': 3, 'campusx': 0, 'write': 4, 'comment': 1}

In [ ]:
# Problem 1
# Apply all the preprocessing techniques that you think are necessary

# Problem 2
# Find out the number of words in the entire corpus and also the total number of unique words (vocabulary) using just python

# Problem 3
# Apply One Hot Encoding

# Problem 4
# Apply bag words and find the vocabulary also find the times each word has occured

# Problem 5
# Apply bag of bi-gram and bag of tri-gram and write down your observation about the dimensionality of the vocabulary

# Problem 6
# Apply tf-idf and find out the idf scores of words, also find out the vocabulary.
