In [23]:
import numpy as np
from collections import Counter

class KNN:
    def __init__(self, k=3, task='classification'):
        self.k = k
        self.task = task

    def fit(self, X, y):
        # KNN doesn't learn → just stores data
        self.X_train = X
        self.y_train = y

    def _distance(self, x1, x2):
        return np.sqrt(np.sum((x1 - x2) ** 2))

    def _predict_one(self, x):
        # Compute distances to all training points
        distances = [self._distance(x, x_train) for x_train in self.X_train]

        # Get k nearest indices
        k_indices = np.argsort(distances)[:self.k]
        for ki in k_indices:
            point = self.X_train[ki]
            label = self.y_train[ki]
            print(f"Index: {ki}, Point: {point}, Label: {label}, Distance: {distances[ki]:.4f}")

        # Get labels of k nearest neighbors
        k_nearest_labels = [self.y_train[i] for i in k_indices]

        # Classification
        if self.task == 'classification':
            return Counter(k_nearest_labels).most_common(1)[0][0]

        # Regression
        elif self.task == 'regression':
            return np.mean(k_nearest_labels)

    def predict(self, X):
        return np.array([self._predict_one(x) for x in X])

In [27]:
X = np.array([[1,2], [2,3], [3,4], [6,7]])
y = np.array([0, 0, 0, 1])

model = KNN(k=3, task='classification')
model.fit(X, y)

# print(model.predict(np.array([[2,2]])))
print(model.predict(np.array([[5,6]])))

Index: 3, Point: [6 7], Label: 1, Distance: 1.4142
Index: 2, Point: [3 4], Label: 0, Distance: 2.8284
Index: 1, Point: [2 3], Label: 0, Distance: 4.2426
[0]


In [32]:
X = np.array([[1], [2], [3], [4]])
y = np.array([2, 4, 6, 8])

model = KNN(k=2, task='regression')
model.fit(X, y)

print(model.predict(np.array([[2.5]])))

Index: 1, Point: [2], Label: 4, Distance: 0.5000
Index: 2, Point: [3], Label: 6, Distance: 0.5000
[5.]


In [33]:
arr = [1,1,1,2,3,4,4,4,4,4]
c = Counter(arr)

In [36]:
c.most_common(3)[0]

(4, 5)

In [37]:
c.most_common(3)[0][0]

4

In [38]:
type(c.most_common(3)[0])

tuple

In [43]:
np.array([1,2]) @ np.array([[2],[2]])

array([6])

In [44]:
import numpy as np

A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

print(A @ B)

[[19 22]
 [43 50]]


In [45]:
np.dot(A,B)

array([[19, 22],
       [43, 50]])