In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv('qoute_dataset.csv')

In [3]:
df.head()

,quote,Author
0,“The world as we have created it is a process ...,Albert Einstein
1,"“It is our choices, Harry, that show what we t...",J.K. Rowling
2,“There are only two ways to live your life. On...,Albert Einstein
3,"“The person, be it gentleman or lady, who has ...",Jane Austen
4,"“Imperfection is beauty, madness is genius and...",Marilyn Monroe


In [4]:
df.shape

(3038, 2)

In [5]:
quote = df['quote']

In [6]:
quote = quote.str.lower()

In [7]:
import string
translator = str.maketrans('','',string.punctuation)
quote = quote.apply(lambda x: x.translate(translator))

In [8]:
quote

0       “the world as we have created it is a process ...
1       “it is our choices harry that show what we tru...
2       “there are only two ways to live your life one...
3       “the person be it gentleman or lady who has no...
4       “imperfection is beauty madness is genius and ...
                              ...                        
3033         the past beats inside me like a second heart
3034    damn claire warn a guy before you do a facepla...
3035    can you be a girl for a few secondsim always a...
3036    thats what fiction is for its for getting at t...
3037    if we have no peace it is because we have forg...
Name: quote, Length: 3038, dtype: object

In [9]:
 from tensorflow.keras.preprocessing.text import Tokenizer

In [10]:
vocab_size = 10000
tokenizer = Tokenizer(num_words=vocab_size)
tokenizer.fit_on_texts(quote)

In [11]:
word_index = tokenizer.word_index
print(len(word_index))
list(word_index.items())[:10]

8978


[('the', 1),
 ('you', 2),
 ('to', 3),
 ('and', 4),
 ('a', 5),
 ('i', 6),
 ('is', 7),
 ('of', 8),
 ('that', 9),
 ('it', 10)]

In [12]:
sequence = tokenizer.texts_to_sequences(quote)

In [13]:
for i in range(1,4):
    print(quote.iloc[i])

“it is our choices harry that show what we truly are far more than our abilities”
“there are only two ways to live your life one is as though nothing is a miracle the other is as though everything is a miracle”
“the person be it gentleman or lady who has not pleasure in a good novel must be intolerably stupid”


In [14]:
for i in range(1,4):
    print(sequence[i])

[947, 7, 70, 871, 373, 9, 433, 21, 19, 465, 14, 294, 52, 54, 70, 3676]
[1337, 14, 53, 201, 714, 3, 81, 15, 36, 37, 7, 29, 329, 93, 7, 5, 1157, 1, 101, 7, 29, 329, 126, 7, 5, 3677]
[713, 116, 12, 10, 2462, 32, 1043, 30, 82, 13, 601, 11, 5, 74, 1338, 119, 12, 2463, 3678]


In [15]:
len(sequence)

3038

In [16]:
x = []
y = []

for seq in sequence:
    for i in range(1,len(seq)):
        inp_seq = seq[:i]
        op_seq = seq[i]
        x.append(inp_seq)
        y.append(op_seq)

In [17]:
x[:35]

[[713],
 [713, 62],
 [713, 62, 29],
 [713, 62, 29, 19],
 [713, 62, 29, 19, 16],
 [713, 62, 29, 19, 16, 946],
 [713, 62, 29, 19, 16, 946, 10],
 [713, 62, 29, 19, 16, 946, 10, 7],
 [713, 62, 29, 19, 16, 946, 10, 7, 5],
 [713, 62, 29, 19, 16, 946, 10, 7, 5, 1156],
 [713, 62, 29, 19, 16, 946, 10, 7, 5, 1156, 8],
 [713, 62, 29, 19, 16, 946, 10, 7, 5, 1156, 8, 70],
 [713, 62, 29, 19, 16, 946, 10, 7, 5, 1156, 8, 70, 293],
 [713, 62, 29, 19, 16, 946, 10, 7, 5, 1156, 8, 70, 293, 10],
 [713, 62, 29, 19, 16, 946, 10, 7, 5, 1156, 8, 70, 293, 10, 145],
 [713, 62, 29, 19, 16, 946, 10, 7, 5, 1156, 8, 70, 293, 10, 145, 12],
 [713, 62, 29, 19, 16, 946, 10, 7, 5, 1156, 8, 70, 293, 10, 145, 12, 809],
 [713, 62, 29, 19, 16, 946, 10, 7, 5, 1156, 8, 70, 293, 10, 145, 12, 809, 104],
 [713,
  62,
  29,
  19,
  16,
  946,
  10,
  7,
  5,
  1156,
  8,
  70,
  293,
  10,
  145,
  12,
  809,
  104,
  752],
 [713,
  62,
  29,
  19,
  16,
  946,
  10,
  7,
  5,
  1156,
  8,
  70,
  293,
  10,
  145,
  12,
  809,
  

In [18]:
len(x)

85271

In [1]:
len(y)

NameError: name 'y' is not defined

In [20]:
max_len = max(len(xl) for xl in x)
max_len

745

In [21]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
x_padded = pad_sequences(x,maxlen=x_len,padding = 'post')

In [22]:
x_padded

array([[713,   0,   0, ...,   0,   0,   0],
       [713,  62,   0, ...,   0,   0,   0],
       [713,  62,  29, ...,   0,   0,   0],
       ...,
       [ 20,  19,  16, ...,   0,   0,   0],
       [ 20,  19,  16, ...,   0,   0,   0],
       [ 20,  19,  16, ...,   0,   0,   0]])

In [23]:
y = np.array(y)

In [24]:
x_padded.shape

(85271, 745)

In [25]:
y.shape

(85271,)

In [26]:
np.unique(y,return_counts=True)

(array([   1,    2,    3, ..., 8976, 8977, 8978]),
 array([3296, 2650, 2704, ...,    1,    1,    1], dtype=int64))

In [27]:
from tensorflow.keras.utils import to_categorical
yohe = to_categorical(y,num_classes=vocab_size)

In [28]:
yohe.shape

(85271, 10000)

In [29]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM,SimpleRNN,Embedding,Dense

In [30]:
embedding_dim = 50
rnn_units = 128

In [31]:
rnn_model = Sequential()

rnn_model.add(
    Embedding(input_dim=vocab_size, output_dim=embedding_dim,
             input_length=max_len)
)
rnn_model.add(SimpleRNN(units=rnn_units))
rnn_model.add(Dense(units=vocab_size, activation='softmax'))

In [32]:
rnn_model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

In [33]:
rnn_model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding (Embedding)                │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ simple_rnn (SimpleRNN)               │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense (Dense)                        │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [34]:
lstm_model = Sequential()
lstm_model.add(
    Embedding(input_dim=vocab_size,output_dim=embedding_dim,
              input_length=max_len)
)
lstm_model.add(LSTM(units=rnn_units))
lstm_model.add(Dense(units=vocab_size,activation='softmax'))

In [35]:
lstm_model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

In [36]:
epochs = 100
batch_size = 120

In [37]:
history_rnn = rnn_model.fit(
    x_padded,yohe,
    epochs=epochs,batch_size=batch_size,
    validation_split=0.1
)  
# This will take a lot of time.

Epoch 1/100
640/640 ━━━━━━━━━━━━━━━━━━━━ 150s 231ms/step - accuracy: 0.0367 - loss: 6.8190 - val_accuracy: 0.0339 - val_loss: 6.8510
Epoch 2/100
640/640 ━━━━━━━━━━━━━━━━━━━━ 187s 292ms/step - accuracy: 0.0369 - loss: 6.6476 - val_accuracy: 0.0314 - val_loss: 6.9622
Epoch 3/100
640/640 ━━━━━━━━━━━━━━━━━━━━ 200s 289ms/step - accuracy: 0.0372 - loss: 6.5791 - val_accuracy: 0.0365 - val_loss: 6.9802
Epoch 4/100
640/640 ━━━━━━━━━━━━━━━━━━━━ 185s 288ms/step - accuracy: 0.0368 - loss: 6.5530 - val_accuracy: 0.0361 - val_loss: 7.0063
Epoch 5/100
640/640 ━━━━━━━━━━━━━━━━━━━━ 188s 293ms/step - accuracy: 0.0377 - loss: 6.5339 - val_accuracy: 0.0332 - val_loss: 7.0772
Epoch 6/100
640/640 ━━━━━━━━━━━━━━━━━━━━ 200s 290ms/step - accuracy: 0.0369 - loss: 6.5190 - val_accuracy: 0.0331 - val_loss: 7.0489
Epoch 7/100
640/640 ━━━━━━━━━━━━━━━━━━━━ 202s 290ms/step - accuracy: 0.0368 - loss: 6.5229 - val_accuracy: 0.0365 - val_loss: 7.0545
Epoch 8/100
640/640 ━━━━━━━━━━━━━━━━━━━━ 202s 290ms/step - accuracy: 

In [ ]:
history_lstm = lstm_model.fit(
    x_padded,yohe,
    epochs=epochs,batch_size=batch_size,
    validation_split=0.1
)  
# This will take a lot of time.

In [ ]:
import tensorflow as tf

print("Num GPUs:", len(tf.config.list_physical_devices('GPU')))

In [ ]:
from tensorflow.keras.models import load_model

lstm_model = load_model("lstm_model.h5")

In [ ]:
lstm_model.save("lstm_model.h5")

In [ ]:
index_to_word = {}
for word, index in word_index.items():
  index_to_word[index] = word
     

from tensorflow.keras.preprocessing.sequence import pad_sequences

In [ ]:
def predictor(model,tokenizer,text,max_len):
  text = text.lower()

  seq = tokenizer.texts_to_sequences([text])[0]
  seq = pad_sequences([seq], maxlen=max_len, padding='pre')

  pred = model.predict(seq,verbose = 0)
  pred_index = np.argmax(pred)
  return index_to_word[pred_index]

In [ ]:
seed_text = "what are you"
next_word = predictor(lstm_model,tokinizer,seed_text,max_len)
print(next_word)

In [ ]:
def generate_text(model,tokenizer,seed_text,max_len,n_words):
  for _ in range(n_words):
    next_word = predictor(model,tokenizer,seed_text,max_len)
    if next_word == "":
      break
    seed_text += " " + next_word
  return seed_text

In [ ]:
seed = "are you a "
generate_text = generate_text(lstm_model,tokinizer,seed,max_len,10)
print(generate_text)

In [ ]:
import pickle
with open("tokenizer.pkl", "wb") as f:
  pickle.dump(tokinizer, f)
     

with open("max_len.pkl", "wb") as f:
  pickle.dump(max_len, f)

In [ ]:
lstm_model.save('/content/drive/MyDrive/Kshitij/lstm_model.keras')

In [ ]:
lstm_model.save('rnn_model.h5')