In [2]:
import numpy as np
arr = np.arange(5,30,2)
boolArr = (arr < 25) & (arr>5) & (arr%3==0)
newArr = arr[boolArr]

In [3]:
arr

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

In [4]:
newArr

array([ 9, 15, 21])

In [5]:
newArr = arr[(arr>5) & (arr<25) & (arr%3==0)]
newArr

array([ 9, 15, 21])

In [6]:
whfnc=np.where((arr<25) & (arr%3==0) & (arr%3==0))
arr[whfnc]

array([ 9, 15, 21])

In [7]:
arr[np.all([arr<25, arr%3==0, arr>5], axis=0)]

array([ 9, 15, 21])

In [8]:
boolArr = arr < 25 & arr>5 & arr%3==0
newArr = arr[boolArr]

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [9]:
from collections import Counter

In [10]:
a = [1,2,3,4,5,5,6]
c = Counter(a)

In [13]:
c[100]

0