In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [3]:
arr2 = np.array([1,2,3,4.5])
type(arr2)

numpy.ndarray

In [4]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
arr = np.zeros((4,2))
arr

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [6]:
arr = np.ones((4,2))
arr

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [7]:
arr = np.linspace(1,5,3)
arr

array([1., 3., 5.])

In [8]:
#Random
np.random.rand(10)
# [0,1]

array([0.64607573, 0.08436868, 0.05407584, 0.99015759, 0.38912605,
       0.39759211, 0.17072304, 0.67092937, 0.03389365, 0.71506072])

In [9]:
np.random.randn(10)
# [-3,3]

array([ 0.15407808,  0.55836388, -1.39107419,  0.86262806,  0.09149098,
       -1.02315342, -1.48554835,  0.90634324,  0.23032949,  0.28752834])

In [10]:
np.random.randint(10,30,3)  #prints 3 values in between 10-30

array([15, 19, 27], dtype=int32)

# Array attributes

In [11]:
arr = np.ones((6,5))
arr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [12]:
arr.shape

(6, 5)

In [13]:
arr[0][0] = 10

In [14]:
arr.min()

np.float64(1.0)

In [15]:
arr.max()

np.float64(10.0)

In [16]:
arr.sum()

np.float64(39.0)

In [17]:
np.sum(arr,axis = 1)

array([14.,  5.,  5.,  5.,  5.,  5.])

In [18]:
arr.mean()

np.float64(1.3)

In [19]:
np.mean(arr,axis=1)

array([2.8, 1. , 1. , 1. , 1. , 1. ])

In [20]:
arr.argmax()

np.int64(0)

In [21]:
arr.argmin()

np.int64(1)

In [22]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [23]:
arr = arr.reshape(5,6)

In [24]:
arr.shape

(5, 6)

In [25]:
arr.argmax()

np.int64(29)

In [26]:
arr.argmin()

np.int64(0)

# Indexing and slicing

In [27]:
arr = np.arange(1,99)

In [28]:
arrslice = arr[3:33]

In [29]:
arrslice.min()

np.int64(4)

In [30]:
arr = np.arange(1,99).reshape(7,14)
arr

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28],
       [29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42],
       [43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56],
       [57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70],
       [71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84],
       [85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98]])

In [31]:
arr[0:2,1:3]

array([[ 2,  3],
       [16, 17]])

In [32]:
arr[:,2]

array([ 3, 17, 31, 45, 59, 73, 87])

In [33]:
arr = arr[arr%2 == 0]
arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68,
       70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [34]:
arr.shape

(49,)

In [35]:
l = [1,2,3,4]
k = l.copy()
k[0] = 110

In [36]:
k

[110, 2, 3, 4]

In [37]:
l

[1, 2, 3, 4]

In [38]:
a = np.arange(1,5).reshape(2,2)
b = np.arange(5,9).reshape(2,2)

In [39]:
a

array([[1, 2],
       [3, 4]])

In [40]:
b

array([[5, 6],
       [7, 8]])

In [41]:
a*b

array([[ 5, 12],
       [21, 32]])

In [42]:
np.dot(a,b)

array([[19, 22],
       [43, 50]])

In [43]:
a = np.arange(1,5)
b = np.arange(5,9)

In [44]:
c = np.vstack((a,b))

In [45]:
c

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [46]:
c = np.hstack((a,b))

In [47]:
c

array([1, 2, 3, 4, 5, 6, 7, 8])

In [48]:
c = np.column_stack((a,b))

In [49]:
c

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [50]:
np.hsplit(c,4)

ValueError: array split does not result in an equal division

In [ ]:
np.vsplit(c,2)

In [ ]:
arr = np.arange(1,99).reshape(7,14)
arr

In [ ]:
arr[:,7].max()

In [ ]:
arr[(arr[:,6] > 90) & (arr[:,5] > 90)]